version: '3.8'
services:
  # Run the database
  db:
    image: mongo
    container_name: smartcamDB
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - C:\Repositorios\SmartCam\database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  # Run the webservice
  ws:
    build: /webservice/
    container_name: smartcamWS
    ports: 
      - 8000:5000
    restart: unless-stopped