version: '3.8'
services:
  # Run the database
  db:
    image: arm64v8/mongo
    container_name: smartcamdb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=henriquegf12
    - MONGO_INITDB_ROOT_PASSWORD=jgs3er4b
    volumes:
    - /home/repositorios/SmartCam/db:/data/db
    ports:
    - 27017:27017