version: '3.8'
services:
  # Run the database
  db:
    image: mongo
    container_name: smartcamdb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=henriquegf12
    - MONGO_INITDB_ROOT_PASSWORD=jgs3er4b
    volumes:
    - /home/smartcamDB:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped